### ISSUE TITLE
TODO RPA

### ISSUE THREAD

**Issue by VinEckSie** [VinEckSie/PowerPlatformSolutions#51]
- [ ] dress the plan according to the docs

- [ ] wait next meeting next thursday

- [ ] make exercises

- [ ] mix example of chat gpt about pa pad and pbi with the fact to

- [ ] interact with contosoinvoicing apps (check all action we can do in this application)

- [ ] add a step to to use action regarding open a browser and fill informations

i think about one cloud flow that when we receive an email we call the desktop flow to put information about an invoice on the invoice contoso app. either informations are in the body of the mail, either wehave to extract to a pdf joined file

- [ ] issue . check if pdf extraction is possible and checke with parallel desktop how to add this machine to a machine group this is mandtaroy to call desktop flow from pa

- [ ] use try catch scope on cloud flow and onerror block on desktop  

flow

- [ ] child flow with cloud flow
