### ISSUE TITLE
TODO Profile

### ISSUE THREAD

**Issue by VinEckSie** [VinEckSie/PowerPlatformSolutions#52]
- [ ] take picture

- [ ] mak article and youtube

- [ ] linkedin : créer liens vers projets

- [ ] article : surveiller et presenter les maj de MS

- [ ] https://chatgpt.com/c/f8cb946a-a6c9-4591-a4d8-22a8d583c873

- [ ] https://chatgpt.com/c/d83766ee-a408-4b76-b36f-efd9eaa9df66
